#!/usr/bin/env bash
#transfers a file from our client to a server:
#Accepts 4 parameters
#The path to the file to be transferred
#The IP of the server we want to transfer the file to
#The username scp connects with
#The path to the SSH private key that scp uses
#Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
#scp must transfer the file to the user home directory ~/
#Strict host key checking must be disabled when using scp
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Use scp to transfer the file to the user's home directory on the server
# Disable strict host key checking with the "-o StrictHostKeyChecking=no" option
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"

# Check the exit status of the scp command
if [ $? -eq 0 ]; then
    echo "File transferred successfully to $USERNAME@$IP:~/"
else
    echo "File transfer failed."
fi
