#!/usr/bin/env bash
# the script Configures Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
STRING="Hello World!"

REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

FILE="/etc/nginx/sites-available/default"
ERRORFILE="/usr/share/nginx/html/404error.html"
FOUR="Ceci n'est pas une page"
ERRORREDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo "$STRING" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Insert the redirect configuration using sudo and tee
echo -e "$REDIRECT" | sudo tee -a "$FILE" > /dev/null

# Create the custom 404 error file
echo "$FOUR" | sudo tee "$ERRORFILE" > /dev/null

# Insert the error redirect configuration using sudo and tee
echo -e "$ERRORREDIRECT" | sudo tee -a "$FILE" > /dev/null

sudo /etc/init.d/nginx restart
