#!/usr/bin/env bash
var=$(hostname)
new_string2="server {\n\tadd_header X-Served-By $var;"

# Edit Nginx configuration to include custom header
sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default
# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo /etc/init.d/nginx restart

