#!/usr/bin/env bash
# Configure Nginx to redirect /redirect_me and create a custom 404 page
var=$(hostname)
new_string2="server {\n\tadd_header X-Served-By $var;"

# Edit Nginx configuration to include custom header
sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default
# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo /etc/init.d/nginx restart

