#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server with frontend and backend using direct assignment
# Update the package list and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Define the HAProxy configuration for frontend and backend using direct assignment
haproxy_config="
frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 276366-web-01 35.175.130.26:80 check
    server 276366-web-02 54.158.191.169:80 check
"

# Append the HAProxy configuration to the HAProxy configuration file
echo "$haproxy_config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# Restart HAProxy
sudo service haproxy restart
